//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.i8n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP.i8n.EntityStrings", typeof(EntityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AppUser.
        /// </summary>
        public static string AddAspNetUser {
            get {
                return ResourceManager.GetString("AddAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New AppUser.
        /// </summary>
        public static string AddNewAspNetUser {
            get {
                return ResourceManager.GetString("AddNewAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Company.
        /// </summary>
        public static string AddNewCompany {
            get {
                return ResourceManager.GetString("AddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Contact.
        /// </summary>
        public static string AddNewContact {
            get {
                return ResourceManager.GetString("AddNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Process.
        /// </summary>
        public static string AddNewProcess {
            get {
                return ResourceManager.GetString("AddNewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Process Step.
        /// </summary>
        public static string AddNewProcessStep {
            get {
                return ResourceManager.GetString("AddNewProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Process Step Template.
        /// </summary>
        public static string AddNewProcessStepTemplate {
            get {
                return ResourceManager.GetString("AddNewProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Process Template.
        /// </summary>
        public static string AddNewProcessTemplate {
            get {
                return ResourceManager.GetString("AddNewProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        public static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product Category.
        /// </summary>
        public static string AddNewProductCategory {
            get {
                return ResourceManager.GetString("AddNewProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Purchase Order.
        /// </summary>
        public static string AddNewPurchaseOrder {
            get {
                return ResourceManager.GetString("AddNewPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Size Rate.
        /// </summary>
        public static string AddNewSizeRate {
            get {
                return ResourceManager.GetString("AddNewSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sizing.
        /// </summary>
        public static string AddNewSizing {
            get {
                return ResourceManager.GetString("AddNewSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sizing Standard.
        /// </summary>
        public static string AddNewSizingStandard {
            get {
                return ResourceManager.GetString("AddNewSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Supplier.
        /// </summary>
        public static string AddNewSupplier {
            get {
                return ResourceManager.GetString("AddNewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Process.
        /// </summary>
        public static string AddProcess {
            get {
                return ResourceManager.GetString("AddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Process Step.
        /// </summary>
        public static string AddProcessStep {
            get {
                return ResourceManager.GetString("AddProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Process Step Template.
        /// </summary>
        public static string AddProcessStepTemplate {
            get {
                return ResourceManager.GetString("AddProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Process Template.
        /// </summary>
        public static string AddProcessTemplate {
            get {
                return ResourceManager.GetString("AddProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Category.
        /// </summary>
        public static string AddProductCategory {
            get {
                return ResourceManager.GetString("AddProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase Order.
        /// </summary>
        public static string AddPurchaseOrder {
            get {
                return ResourceManager.GetString("AddPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove AppUser.
        /// </summary>
        public static string AddRemoveAspNetUser {
            get {
                return ResourceManager.GetString("AddRemoveAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Company.
        /// </summary>
        public static string AddRemoveCompany {
            get {
                return ResourceManager.GetString("AddRemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Contact.
        /// </summary>
        public static string AddRemoveContact {
            get {
                return ResourceManager.GetString("AddRemoveContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Customer.
        /// </summary>
        public static string AddRemoveCustomer {
            get {
                return ResourceManager.GetString("AddRemoveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Process.
        /// </summary>
        public static string AddRemoveProcess {
            get {
                return ResourceManager.GetString("AddRemoveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Process Step.
        /// </summary>
        public static string AddRemoveProcessStep {
            get {
                return ResourceManager.GetString("AddRemoveProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Process Step Template.
        /// </summary>
        public static string AddRemoveProcessStepTemplate {
            get {
                return ResourceManager.GetString("AddRemoveProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Process Template.
        /// </summary>
        public static string AddRemoveProcessTemplate {
            get {
                return ResourceManager.GetString("AddRemoveProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Product.
        /// </summary>
        public static string AddRemoveProduct {
            get {
                return ResourceManager.GetString("AddRemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Product Category.
        /// </summary>
        public static string AddRemoveProductCategory {
            get {
                return ResourceManager.GetString("AddRemoveProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Purchase Order.
        /// </summary>
        public static string AddRemovePurchaseOrder {
            get {
                return ResourceManager.GetString("AddRemovePurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Size Rate.
        /// </summary>
        public static string AddRemoveSizeRate {
            get {
                return ResourceManager.GetString("AddRemoveSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Sizing.
        /// </summary>
        public static string AddRemoveSizing {
            get {
                return ResourceManager.GetString("AddRemoveSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Sizing Standard.
        /// </summary>
        public static string AddRemoveSizingStandard {
            get {
                return ResourceManager.GetString("AddRemoveSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Supplier.
        /// </summary>
        public static string AddRemoveSupplier {
            get {
                return ResourceManager.GetString("AddRemoveSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Size Rate.
        /// </summary>
        public static string AddSizeRate {
            get {
                return ResourceManager.GetString("AddSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sizing.
        /// </summary>
        public static string AddSizing {
            get {
                return ResourceManager.GetString("AddSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sizing Standard.
        /// </summary>
        public static string AddSizingStandard {
            get {
                return ResourceManager.GetString("AddSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Date.
        /// </summary>
        public static string ApproveDate {
            get {
                return ResourceManager.GetString("ApproveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved User.
        /// </summary>
        public static string ApprovedUser {
            get {
                return ResourceManager.GetString("ApprovedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved User ID.
        /// </summary>
        public static string ApprovedUserId {
            get {
                return ResourceManager.GetString("ApprovedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved User IP.
        /// </summary>
        public static string ApprovedUserIp {
            get {
                return ResourceManager.GetString("ApprovedUserIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUser.
        /// </summary>
        public static string AspNetUser {
            get {
                return ResourceManager.GetString("AspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUsers.
        /// </summary>
        public static string AspNetUsers {
            get {
                return ResourceManager.GetString("AspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUsers List.
        /// </summary>
        public static string AspNetUsersList {
            get {
                return ResourceManager.GetString("AspNetUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Date.
        /// </summary>
        public static string CancelDate {
            get {
                return ResourceManager.GetString("CancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled User.
        /// </summary>
        public static string CancelledUser {
            get {
                return ResourceManager.GetString("CancelledUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled User Id.
        /// </summary>
        public static string CancelledUserId {
            get {
                return ResourceManager.GetString("CancelledUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled User Ip.
        /// </summary>
        public static string CancelledUserIp {
            get {
                return ResourceManager.GetString("CancelledUserIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Notes.
        /// </summary>
        public static string CancelNotes {
            get {
                return ResourceManager.GetString("CancelNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies List.
        /// </summary>
        public static string CompaniesList {
            get {
                return ResourceManager.GetString("CompaniesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts List.
        /// </summary>
        public static string ContactsList {
            get {
                return ResourceManager.GetString("ContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AppUser.
        /// </summary>
        public static string CreateAspNetUser {
            get {
                return ResourceManager.GetString("CreateAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Company.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created User.
        /// </summary>
        public static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process.
        /// </summary>
        public static string CreateProcess {
            get {
                return ResourceManager.GetString("CreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process Step.
        /// </summary>
        public static string CreateProcessStep {
            get {
                return ResourceManager.GetString("CreateProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process Step Template.
        /// </summary>
        public static string CreateProcessStepTemplate {
            get {
                return ResourceManager.GetString("CreateProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process Template.
        /// </summary>
        public static string CreateProcessTemplate {
            get {
                return ResourceManager.GetString("CreateProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Category.
        /// </summary>
        public static string CreateProductCategory {
            get {
                return ResourceManager.GetString("CreateProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Purchase Order.
        /// </summary>
        public static string CreatePurchaseOrder {
            get {
                return ResourceManager.GetString("CreatePurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Size Rate.
        /// </summary>
        public static string CreateSizeRate {
            get {
                return ResourceManager.GetString("CreateSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sizing.
        /// </summary>
        public static string CreateSizing {
            get {
                return ResourceManager.GetString("CreateSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sizing Standard.
        /// </summary>
        public static string CreateSizingStandard {
            get {
                return ResourceManager.GetString("CreateSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Supplier.
        /// </summary>
        public static string CreateSupplier {
            get {
                return ResourceManager.GetString("CreateSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string CreatorId {
            get {
                return ResourceManager.GetString("CreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator Ip.
        /// </summary>
        public static string CreatorIp {
            get {
                return ResourceManager.GetString("CreatorIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        public static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Title.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete AppUser.
        /// </summary>
        public static string DeleteAspNetUser {
            get {
                return ResourceManager.GetString("DeleteAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Company.
        /// </summary>
        public static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        public static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Process.
        /// </summary>
        public static string DeleteProcess {
            get {
                return ResourceManager.GetString("DeleteProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Process Step.
        /// </summary>
        public static string DeleteProcessStep {
            get {
                return ResourceManager.GetString("DeleteProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Process Step Template.
        /// </summary>
        public static string DeleteProcessStepTemplate {
            get {
                return ResourceManager.GetString("DeleteProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Process Template.
        /// </summary>
        public static string DeleteProcessTemplate {
            get {
                return ResourceManager.GetString("DeleteProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Category.
        /// </summary>
        public static string DeleteProductCategory {
            get {
                return ResourceManager.GetString("DeleteProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Purchase Order.
        /// </summary>
        public static string DeletePurchaseOrder {
            get {
                return ResourceManager.GetString("DeletePurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Size Rate.
        /// </summary>
        public static string DeleteSizeRate {
            get {
                return ResourceManager.GetString("DeleteSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sizing.
        /// </summary>
        public static string DeleteSizing {
            get {
                return ResourceManager.GetString("DeleteSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sizing Standard.
        /// </summary>
        public static string DeleteSizingStandard {
            get {
                return ResourceManager.GetString("DeleteSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Supplier.
        /// </summary>
        public static string DeleteSupplier {
            get {
                return ResourceManager.GetString("DeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Discontinued {
            get {
                return ResourceManager.GetString("Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinue Date.
        /// </summary>
        public static string DiscontinueDate {
            get {
                return ResourceManager.GetString("DiscontinueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued User.
        /// </summary>
        public static string DiscontinuedUser {
            get {
                return ResourceManager.GetString("DiscontinuedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued User Id.
        /// </summary>
        public static string DiscontinuedUserId {
            get {
                return ResourceManager.GetString("DiscontinuedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued User Ip.
        /// </summary>
        public static string DiscontinuedUserIp {
            get {
                return ResourceManager.GetString("DiscontinuedUserIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinue Notes.
        /// </summary>
        public static string DiscontinueNotes {
            get {
                return ResourceManager.GetString("DiscontinueNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit AppUser.
        /// </summary>
        public static string EditAspNetUser {
            get {
                return ResourceManager.GetString("EditAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Process.
        /// </summary>
        public static string EditProcess {
            get {
                return ResourceManager.GetString("EditProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Process Step.
        /// </summary>
        public static string EditProcessStep {
            get {
                return ResourceManager.GetString("EditProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Process Step Template.
        /// </summary>
        public static string EditProcessStepTemplate {
            get {
                return ResourceManager.GetString("EditProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Process Template.
        /// </summary>
        public static string EditProcessTemplate {
            get {
                return ResourceManager.GetString("EditProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Category.
        /// </summary>
        public static string EditProductCategory {
            get {
                return ResourceManager.GetString("EditProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Purchase Order.
        /// </summary>
        public static string EditPurchaseOrder {
            get {
                return ResourceManager.GetString("EditPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Size Rate.
        /// </summary>
        public static string EditSizeRate {
            get {
                return ResourceManager.GetString("EditSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sizing.
        /// </summary>
        public static string EditSizing {
            get {
                return ResourceManager.GetString("EditSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sizing Standard.
        /// </summary>
        public static string EditSizingStandard {
            get {
                return ResourceManager.GetString("EditSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supplier.
        /// </summary>
        public static string EditSupplier {
            get {
                return ResourceManager.GetString("EditSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Home.
        /// </summary>
        public static string EmailHome {
            get {
                return ResourceManager.GetString("EmailHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Work.
        /// </summary>
        public static string EmailWork {
            get {
                return ResourceManager.GetString("EmailWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Date.
        /// </summary>
        public static string ForecastDate {
            get {
                return ResourceManager.GetString("ForecastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Nr.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string IsCompleted {
            get {
                return ResourceManager.GetString("IsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified User.
        /// </summary>
        public static string ModifiedUser {
            get {
                return ResourceManager.GetString("ModifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string ModifierId {
            get {
                return ResourceManager.GetString("ModifierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Ip.
        /// </summary>
        public static string ModifierIp {
            get {
                return ResourceManager.GetString("ModifierIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Date.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Nr.
        /// </summary>
        public static string ModifyNr {
            get {
                return ResourceManager.GetString("ModifyNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string ParentCategoryId {
            get {
                return ResourceManager.GetString("ParentCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone3.
        /// </summary>
        public static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string PhoneMobile {
            get {
                return ResourceManager.GetString("PhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Work1.
        /// </summary>
        public static string PhoneWork1 {
            get {
                return ResourceManager.GetString("PhoneWork1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Work2.
        /// </summary>
        public static string PhoneWork2 {
            get {
                return ResourceManager.GetString("PhoneWork2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes List.
        /// </summary>
        public static string ProcessesList {
            get {
                return ResourceManager.GetString("ProcessesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step.
        /// </summary>
        public static string ProcessStep {
            get {
                return ResourceManager.GetString("ProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Steps.
        /// </summary>
        public static string ProcessSteps {
            get {
                return ResourceManager.GetString("ProcessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Steps List.
        /// </summary>
        public static string ProcessStepsList {
            get {
                return ResourceManager.GetString("ProcessStepsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step Template.
        /// </summary>
        public static string ProcessStepTemplate {
            get {
                return ResourceManager.GetString("ProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step Templates.
        /// </summary>
        public static string ProcessStepTemplates {
            get {
                return ResourceManager.GetString("ProcessStepTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step Templates List.
        /// </summary>
        public static string ProcessStepTemplatesList {
            get {
                return ResourceManager.GetString("ProcessStepTemplatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Template.
        /// </summary>
        public static string ProcessTemplate {
            get {
                return ResourceManager.GetString("ProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Template.
        /// </summary>
        public static string ProcessTemplateId {
            get {
                return ResourceManager.GetString("ProcessTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Templates.
        /// </summary>
        public static string ProcessTemplates {
            get {
                return ResourceManager.GetString("ProcessTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Templates List.
        /// </summary>
        public static string ProcessTemplatesList {
            get {
                return ResourceManager.GetString("ProcessTemplatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories List.
        /// </summary>
        public static string ProductCategoriesList {
            get {
                return ResourceManager.GetString("ProductCategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string ProductsList {
            get {
                return ResourceManager.GetString("ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrderId {
            get {
                return ResourceManager.GetString("PurchaseOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        public static string PurchaseOrders {
            get {
                return ResourceManager.GetString("PurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders List.
        /// </summary>
        public static string PurchaseOrdersList {
            get {
                return ResourceManager.GetString("PurchaseOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized Date.
        /// </summary>
        public static string RealizedDate {
            get {
                return ResourceManager.GetString("RealizedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove AppUser.
        /// </summary>
        public static string RemoveAspNetUser {
            get {
                return ResourceManager.GetString("RemoveAspNetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Company.
        /// </summary>
        public static string RemoveCompany {
            get {
                return ResourceManager.GetString("RemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Contact.
        /// </summary>
        public static string RemoveContact {
            get {
                return ResourceManager.GetString("RemoveContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Customer.
        /// </summary>
        public static string RemoveCustomer {
            get {
                return ResourceManager.GetString("RemoveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Process.
        /// </summary>
        public static string RemoveProcess {
            get {
                return ResourceManager.GetString("RemoveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Process Step.
        /// </summary>
        public static string RemoveProcessStep {
            get {
                return ResourceManager.GetString("RemoveProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Process Step Template.
        /// </summary>
        public static string RemoveProcessStepTemplate {
            get {
                return ResourceManager.GetString("RemoveProcessStepTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Process Template.
        /// </summary>
        public static string RemoveProcessTemplate {
            get {
                return ResourceManager.GetString("RemoveProcessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product.
        /// </summary>
        public static string RemoveProduct {
            get {
                return ResourceManager.GetString("RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product Category.
        /// </summary>
        public static string RemoveProductCategory {
            get {
                return ResourceManager.GetString("RemoveProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Purchase Order.
        /// </summary>
        public static string RemovePurchaseOrder {
            get {
                return ResourceManager.GetString("RemovePurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Size Rate.
        /// </summary>
        public static string RemoveSizeRate {
            get {
                return ResourceManager.GetString("RemoveSizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Sizing.
        /// </summary>
        public static string RemoveSizing {
            get {
                return ResourceManager.GetString("RemoveSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Sizing Standard.
        /// </summary>
        public static string RemoveSizingStandard {
            get {
                return ResourceManager.GetString("RemoveSizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Supplier.
        /// </summary>
        public static string RemoveSupplier {
            get {
                return ResourceManager.GetString("RemoveSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Work Days.
        /// </summary>
        public static string RequiredWorkDays {
            get {
                return ResourceManager.GetString("RequiredWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Rate.
        /// </summary>
        public static string SizeRate {
            get {
                return ResourceManager.GetString("SizeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Rate Divisor.
        /// </summary>
        public static string SizeRateDivisor {
            get {
                return ResourceManager.GetString("SizeRateDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Rates.
        /// </summary>
        public static string SizeRates {
            get {
                return ResourceManager.GetString("SizeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Rates List.
        /// </summary>
        public static string SizeRatesList {
            get {
                return ResourceManager.GetString("SizeRatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string Sizing {
            get {
                return ResourceManager.GetString("Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizings.
        /// </summary>
        public static string Sizings {
            get {
                return ResourceManager.GetString("Sizings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizings List.
        /// </summary>
        public static string SizingsList {
            get {
                return ResourceManager.GetString("SizingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing Standard.
        /// </summary>
        public static string SizingStandard {
            get {
                return ResourceManager.GetString("SizingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing Standard Id.
        /// </summary>
        public static string SizingStandardId {
            get {
                return ResourceManager.GetString("SizingStandardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing Standards.
        /// </summary>
        public static string SizingStandards {
            get {
                return ResourceManager.GetString("SizingStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing Standards List.
        /// </summary>
        public static string SizingStandardsList {
            get {
                return ResourceManager.GetString("SizingStandardsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Templates.
        /// </summary>
        public static string StepTemplates {
            get {
                return ResourceManager.GetString("StepTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories.
        /// </summary>
        public static string SubCategories {
            get {
                return ResourceManager.GetString("SubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string SupplierCode {
            get {
                return ResourceManager.GetString("SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers List.
        /// </summary>
        public static string SuppliersList {
            get {
                return ResourceManager.GetString("SuppliersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string TargetDate {
            get {
                return ResourceManager.GetString("TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
