//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    #region Generated Interfaces
    
    public interface IDisplayOrder
    {
        int DisplayOrder { get; set; }
    }
    
    public interface ICreatorId
    {
        string CreatorId { get; set; }
    }
    
    public interface ICreatorIp
    {
        string CreatorIp { get; set; }
    }
    
    public interface ICreateDate
    {
        System.DateTime CreateDate { get; set; }
    }
    
    public interface IModifyNr
    {
        int ModifyNr { get; set; }
    }
    
    public interface IModifierId
    {
        string ModifierId { get; set; }
    }
    
    public interface IModifierIp
    {
        string ModifierIp { get; set; }
    }
    
    public interface IModifyDate
    {
        System.DateTime ModifyDate { get; set; }
    }
    
    public interface IIsApproved
    {
        int Id { get; set; }
        Nullable<System.DateTime> ApproveDate { get; set; }
        bool IsApproved { get; set; }
    }
    
    public interface IApproval
    {
        Nullable<System.DateTime> ApproveDate { get; set; }
        bool IsApproved { get; set; }
        string ApprovedUserId { get; set; }
        string ApprovedUserIp { get; set; }
    }
    
    public interface IHasProduct
    {
        int ProductId { get; set; }
    }
    
    public interface ICancelled
    {
        bool Cancelled { get; set; }
        Nullable<System.DateTime> CancelDate { get; set; }
        string CancellationReason { get; set; }
    }
    
    public interface ICancellation
    {
        bool Cancelled { get; set; }
        Nullable<System.DateTime> CancelDate { get; set; }
        string CancellationReason { get; set; }
        string CancelledUserId { get; set; }
        string CancelledUserIp { get; set; }
    }
    
    public interface IDiscontinued
    {
        bool Discontinued { get; set; }
        Nullable<System.DateTime> DiscontinueDate { get; set; }
        string DiscontinueNotes { get; set; }
    }
    
    public interface IDiscontinuedUser
    {
        string DiscontinuedUserId { get; set; }
        string DiscontinuedUserIp { get; set; }
    }
    
    public interface ISellingPrice
    {
        decimal UnitPrice { get; set; }
        int SellingCurrencyId { get; set; }
        Nullable<decimal> UnitPrice2 { get; set; }
        Nullable<int> SellingCurrency2Id { get; set; }
    }
    
    public interface IRetailPrice
    {
        Nullable<decimal> RetailPrice { get; set; }
        Nullable<int> RetailCurrencyId { get; set; }
    }
    
    public interface ILicensorPrice
    {
        Nullable<decimal> LicensorPrice { get; set; }
        Nullable<int> LicensorCurrencyId { get; set; }
    }
    
    public interface IRoyaltyFee
    {
        Nullable<decimal> RoyaltyFee { get; set; }
        Nullable<int> RoyaltyCurrencyId { get; set; }
    }
    
    public interface IBuyingPrice
    {
        Nullable<decimal> BuyingPrice { get; set; }
        Nullable<int> BuyingCurrencyId { get; set; }
        Nullable<decimal> BuyingPrice2 { get; set; }
        Nullable<int> BuyingCurrency2Id { get; set; }
    }
    
    public interface IAllPrice
    {
        decimal UnitPrice { get; set; }
        int SellingCurrencyId { get; set; }
        Nullable<decimal> UnitPrice2 { get; set; }
        Nullable<int> SellingCurrency2Id { get; set; }
        Nullable<decimal> RetailPrice { get; set; }
        Nullable<int> RetailCurrencyId { get; set; }
        Nullable<decimal> LicensorPrice { get; set; }
        Nullable<int> LicensorCurrencyId { get; set; }
        Nullable<decimal> RoyaltyFee { get; set; }
        Nullable<int> RoyaltyCurrencyId { get; set; }
        Nullable<decimal> BuyingPrice { get; set; }
        Nullable<int> BuyingCurrencyId { get; set; }
        Nullable<decimal> BuyingPrice2 { get; set; }
        Nullable<int> BuyingCurrency2Id { get; set; }
    }
    
    public interface IAllPriceCurrency
    {
        decimal UnitPrice { get; set; }
        int SellingCurrencyId { get; set; }
        Nullable<decimal> UnitPrice2 { get; set; }
        Nullable<int> SellingCurrency2Id { get; set; }
        Nullable<decimal> RetailPrice { get; set; }
        Nullable<int> RetailCurrencyId { get; set; }
        Nullable<decimal> LicensorPrice { get; set; }
        Nullable<int> LicensorCurrencyId { get; set; }
        Nullable<decimal> RoyaltyFee { get; set; }
        Nullable<int> RoyaltyCurrencyId { get; set; }
        Nullable<decimal> BuyingPrice { get; set; }
        Nullable<int> BuyingCurrencyId { get; set; }
        Nullable<decimal> BuyingPrice2 { get; set; }
        Nullable<int> BuyingCurrency2Id { get; set; }
        Currency SellingCurrency { get; set; }
        Currency SellingCurrency2 { get; set; }
        Currency BuyingCurrency { get; set; }
        Currency BuyingCurrency2 { get; set; }
        Currency RetailCurrency { get; set; }
        Currency RoyaltyCurrency { get; set; }
        Currency LicensorCurrency { get; set; }
    }
    #endregion
}
