//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDepartment : ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDepartment()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public int CustomerId { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        public virtual AspNetUser CreatedUser { get; set; }
        public virtual AspNetUser ModifiedUser { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    	/// <summary>
    	/// Clones all properties in a new CustomerDepartment instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New CustomerDepartment instance</returns>
        public CustomerDepartment Clone()
        {
            var clone = new CustomerDepartment();
            clone.DepartmentName = DepartmentName;
            clone.CustomerId = CustomerId;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. CustomerDepartment.part.cs)
    	// to add more complexity to clone
        partial void Cloning(CustomerDepartment clone);
    }
    
    //Data Transfer Object type for CustomerDepartment
    public partial class CustomerDepartmentDTO
    {
        public CustomerDepartmentDTO() { }
    
        public CustomerDepartmentDTO(CustomerDepartment entity)
        {
            Id = entity.Id;
            DepartmentName = entity.DepartmentName;
            CustomerId = entity.CustomerId;
        
            Initiliazing(entity);
        }
    
        partial void Initiliazing(CustomerDepartment entity);
        
        public virtual CustomerDepartment ToCustomerDepartment()
        {
            var entity = new CustomerDepartment();
            entity.Id = Id;
            entity.DepartmentName = DepartmentName;
            entity.CustomerId = CustomerId;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(CustomerDepartment entity);
      
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public int CustomerId { get; set; }
    }
}
