//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POImage : IDisplayOrder, ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        public int Id { get; set; }
        public int PurchaseOrderId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageTitle { get; set; }
        public int DisplayOrder { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        public virtual AspNetUser CreatedUser { get; set; }
        public virtual AspNetUser ModifiedUser { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    	/// <summary>
    	/// Clones all properties in a new POImage instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New POImage instance</returns>
        public POImage Clone()
        {
            var clone = new POImage();
            clone.PurchaseOrderId = PurchaseOrderId;
            clone.ImageUrl = ImageUrl;
            clone.ImageTitle = ImageTitle;
            clone.DisplayOrder = DisplayOrder;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. POImage.part.cs)
    	// to add more complexity to clone
        partial void Cloning(POImage clone);
    }
    
    //Data Transfer Object type for POImage
    public partial class POImageDTO
    {
        public POImageDTO() { }
    
        public POImageDTO(POImage entity)
        {
            Id = entity.Id;
            PurchaseOrderId = entity.PurchaseOrderId;
            ImageUrl = entity.ImageUrl;
            ImageTitle = entity.ImageTitle;
            DisplayOrder = entity.DisplayOrder;
        
            Initiliazing(entity);
        }
    
        partial void Initiliazing(POImage entity);
        
        public virtual POImage ToPOImage()
        {
            var entity = new POImage();
            entity.Id = Id;
            entity.PurchaseOrderId = PurchaseOrderId;
            entity.ImageUrl = ImageUrl;
            entity.ImageTitle = ImageTitle;
            entity.DisplayOrder = DisplayOrder;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(POImage entity);
      
        public int Id { get; set; }
        public int PurchaseOrderId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageTitle { get; set; }
        public int DisplayOrder { get; set; }
    }
}
