//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantitySizeRate : IDisplayOrder, ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public int PurchaseOrderId { get; set; }
        public int SizeCaptionId { get; set; }
        public int Rate { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual SizeCaption SizeCaption { get; set; }
    	/// <summary>
    	/// Clones all properties in a new QuantitySizeRate instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New QuantitySizeRate instance</returns>
        public QuantitySizeRate Clone()
        {
            var clone = new QuantitySizeRate();
            clone.DisplayOrder = DisplayOrder;
            clone.PurchaseOrderId = PurchaseOrderId;
            clone.SizeCaptionId = SizeCaptionId;
            clone.Rate = Rate;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. QuantitySizeRate.part.cs)
    	// to add more complexity to clone
        partial void Cloning(QuantitySizeRate clone);
    }
    
    //Data Transfer Object type for QuantitySizeRate
    public partial class QuantitySizeRateDTO
    {
        public QuantitySizeRateDTO() { }
    
        public QuantitySizeRateDTO(QuantitySizeRate entity)
        {
            Id = entity.Id;
            DisplayOrder = entity.DisplayOrder;
            PurchaseOrderId = entity.PurchaseOrderId;
            SizeCaptionId = entity.SizeCaptionId;
            Rate = entity.Rate;
        
            Initiliazing(entity);
        }
    
        partial void Initiliazing(QuantitySizeRate entity);
        
        public virtual QuantitySizeRate ToQuantitySizeRate()
        {
            var entity = new QuantitySizeRate();
            entity.Id = Id;
            entity.DisplayOrder = DisplayOrder;
            entity.PurchaseOrderId = PurchaseOrderId;
            entity.SizeCaptionId = SizeCaptionId;
            entity.Rate = Rate;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(QuantitySizeRate entity);
      
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public int PurchaseOrderId { get; set; }
        public int SizeCaptionId { get; set; }
        public int Rate { get; set; }
    }
}
