//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeStandard : ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SizeStandard()
        {
            this.Sizes = new HashSet<Size>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Sizes { get; set; }
    	/// <summary>
    	/// Clones all properties in a new SizeStandard instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New SizeStandard instance</returns>
        public SizeStandard Clone()
        {
            var clone = new SizeStandard();
            clone.Title = Title;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. SizeStandard.part.cs)
    	// to add more complexity to clone
        partial void Cloning(SizeStandard clone);
    }
    
    //Data Transfer Object type for SizeStandard
    public partial class SizeStandardDTO
    {
        public SizeStandardDTO() { }
    
        public SizeStandardDTO(SizeStandard entity)
        {
            Id = entity.Id;
            Title = entity.Title;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(SizeStandard entity);
        
        public virtual SizeStandard ToSizeStandard()
        {
            var entity = new SizeStandard();
            entity.Id = Id;
            entity.Title = Title;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(SizeStandard entity);
      
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
