//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size : IDisplayOrder, ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Size()
        {
            this.SizeQuantities = new HashSet<SizeQuantity>();
        }
    
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string Title { get; set; }
        public int SizeStandardId { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SizeQuantity> SizeQuantities { get; set; }
        public virtual SizeStandard SizeStandard { get; set; }
    	/// <summary>
    	/// Clones all properties in a new Size instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New Size instance</returns>
        public Size Clone()
        {
            var clone = new Size();
            clone.DisplayOrder = DisplayOrder;
            clone.Title = Title;
            clone.SizeStandardId = SizeStandardId;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. Size.part.cs)
    	// to add more complexity to clone
        partial void Cloning(Size clone);
    }
    
    //Data Transfer Object type for Size
    public partial class SizeDTO
    {
        public SizeDTO() { }
    
        public SizeDTO(Size entity)
        {
            Id = entity.Id;
            DisplayOrder = entity.DisplayOrder;
            Title = entity.Title;
            SizeStandardId = entity.SizeStandardId;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(Size entity);
        
        public virtual Size ToSize()
        {
            var entity = new Size();
            entity.Id = Id;
            entity.DisplayOrder = DisplayOrder;
            entity.Title = Title;
            entity.SizeStandardId = SizeStandardId;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Size entity);
      
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string Title { get; set; }
        public int SizeStandardId { get; set; }
    }
}
