//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeQuantity : IDisplayOrder, ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public int PurchaseOrderId { get; set; }
        public int SizeId { get; set; }
        public int Quantity { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Size Size { get; set; }
    	/// <summary>
    	/// Clones all properties in a new SizeQuantity instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New SizeQuantity instance</returns>
        public SizeQuantity Clone()
        {
            var clone = new SizeQuantity();
            clone.DisplayOrder = DisplayOrder;
            clone.PurchaseOrderId = PurchaseOrderId;
            clone.SizeId = SizeId;
            clone.Quantity = Quantity;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. SizeQuantity.part.cs)
    	// to add more complexity to clone
        partial void Cloning(SizeQuantity clone);
    }
    
    //Data Transfer Object type for SizeQuantity
    public partial class SizeQuantityDTO
    {
        public SizeQuantityDTO() { }
    
        public SizeQuantityDTO(SizeQuantity entity)
        {
            Id = entity.Id;
            DisplayOrder = entity.DisplayOrder;
            PurchaseOrderId = entity.PurchaseOrderId;
            SizeId = entity.SizeId;
            Quantity = entity.Quantity;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(SizeQuantity entity);
        
        public virtual SizeQuantity ToSizeQuantity()
        {
            var entity = new SizeQuantity();
            entity.Id = Id;
            entity.DisplayOrder = DisplayOrder;
            entity.PurchaseOrderId = PurchaseOrderId;
            entity.SizeId = SizeId;
            entity.Quantity = Quantity;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(SizeQuantity entity);
      
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public int PurchaseOrderId { get; set; }
        public int SizeId { get; set; }
        public int Quantity { get; set; }
    }
}
