//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizingStandard : ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SizingStandard()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Sizings = new HashSet<Sizing>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sizing> Sizings { get; set; }
        public virtual AspNetUser CreatedUser { get; set; }
        public virtual AspNetUser ModifiedUser { get; set; }
    	/// <summary>
    	/// Clones all properties in a new SizingStandard instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New SizingStandard instance</returns>
        public SizingStandard Clone()
        {
            var clone = new SizingStandard();
            clone.Title = Title;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. SizingStandard.part.cs)
    	// to add more complexity to clone
        partial void Cloning(SizingStandard clone);
    }
    
    //Data Transfer Object type for SizingStandard
    public partial class SizingStandardDTO
    {
        public SizingStandardDTO() { }
    
        public SizingStandardDTO(SizingStandard entity)
        {
            Id = entity.Id;
            Title = entity.Title;
        
            Initiliazing(entity);
        }
    
        partial void Initiliazing(SizingStandard entity);
        
        public virtual SizingStandard ToSizingStandard()
        {
            var entity = new SizingStandard();
            entity.Id = Id;
            entity.Title = Title;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(SizingStandard entity);
      
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
