//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizing : IDisplayOrder, ICreatorId, ICreatorIp, ICreateDate, IModifyNr, IModifierId, IModifierIp, IModifyDate
    {
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string Caption { get; set; }
        public int SizingStandardId { get; set; }
        public int ModifyNr { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifierId { get; set; }
        public string ModifierIp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorId { get; set; }
        public string CreatorIp { get; set; }
    
        public virtual SizingStandard SizingStandard { get; set; }
    	/// <summary>
    	/// Clones all properties in a new Sizing instance,
    	/// except PrimaryKey(s)
    	/// </summary>
    	/// <returns>New Sizing instance</returns>
        public Sizing Clone()
        {
            var clone = new Sizing();
            clone.DisplayOrder = DisplayOrder;
            clone.Caption = Caption;
            clone.SizingStandardId = SizingStandardId;
            clone.ModifyNr = ModifyNr;
            clone.ModifyDate = ModifyDate;
            clone.ModifierId = ModifierId;
            clone.ModifierIp = ModifierIp;
            clone.CreateDate = CreateDate;
            clone.CreatorId = CreatorId;
            clone.CreatorIp = CreatorIp;
    
            Cloning(clone);
    
            return clone;
        }
    
    	// Use below function in a partial class file (eg. Sizing.part.cs)
    	// to add more complexity to clone
        partial void Cloning(Sizing clone);
    }
    
    //Data Transfer Object type for Sizing
    public partial class SizingDTO
    {
        public SizingDTO() { }
    
        public SizingDTO(Sizing entity)
        {
            Id = entity.Id;
            DisplayOrder = entity.DisplayOrder;
            Caption = entity.Caption;
            SizingStandardId = entity.SizingStandardId;
        
            Initiliazing(entity);
        }
    
        partial void Initiliazing(Sizing entity);
        
        public virtual Sizing ToSizing()
        {
            var entity = new Sizing();
            entity.Id = Id;
            entity.DisplayOrder = DisplayOrder;
            entity.Caption = Caption;
            entity.SizingStandardId = SizingStandardId;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Sizing entity);
      
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string Caption { get; set; }
        public int SizingStandardId { get; set; }
    }
}
