using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CP.i8n;
//------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    [MetadataTypeAttribute(typeof(Currency.CurrencyMetadata))]
    public partial class Currency
	{
        internal sealed partial class CurrencyMetadata
		{
            // This metadata class is not intended to be instantiated.
            private CurrencyMetadata() { }

            [StringLength(50, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "CurrencyName")]
            public string CurrencyName { get; set; }

            [StringLength(5, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "CurrencyCode")]
            public string CurrencyCode { get; set; }

            [StringLength(5, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "CurrencySymbol")]
            public string CurrencySymbol { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "IsPublished")]
            public bool IsPublished { get; set; }

		}
	}
}