using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CriticalPath.Data.Resources;
//------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen 10/09/2015 03:17:35
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    [MetadataTypeAttribute(typeof(OrderItem.OrderItemMetadata))]
    public partial class OrderItem
	{
        internal sealed partial class OrderItemMetadata
		{
            // This metadata class is not intended to be instantiated.
            private OrderItemMetadata() { }

            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "PuchaseOrderId")]
            public int PuchaseOrderId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "PuchaseOrder")]
            public PuchaseOrder PuchaseOrder { get; set; }

            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "ProductId")]
            public int ProductId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "Product")]
            public Product Product { get; set; }

            [StringLength(255, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [DataType(DataType.MultilineText)]
            [Display(ResourceType = typeof(EntityStrings), Name = "Notes")]
            public string Notes { get; set; }

		}
	}
}