using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CP.i8n;
//------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//------------------------------------------------------------------------------

namespace CriticalPath.Data
{
    [MetadataTypeAttribute(typeof(Product.ProductMetadata))]
    public partial class Product
	{
        internal sealed partial class ProductMetadata
		{
            // This metadata class is not intended to be instantiated.
            private ProductMetadata() { }

            [StringLength(64, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "ProductCode")]
            public string ProductCode { get; set; }

            [StringLength(128, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [DataType(DataType.Text)]
            [Display(ResourceType = typeof(EntityStrings), Name = "Description")]
            public string Description { get; set; }

            [StringLength(256, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [DataType(DataType.ImageUrl)]
            [Display(ResourceType = typeof(EntityStrings), Name = "ImageUrl")]
            public string ImageUrl { get; set; }

            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "CategoryId")]
            public int CategoryId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "Category")]
            public ProductCategory Category { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "Licensed")]
            public bool Licensed { get; set; }

            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "UnitPrice")]
            public decimal UnitPrice { get; set; }

            [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
            [Display(ResourceType = typeof(EntityStrings), Name = "SellingCurrencyId")]
            public int SellingCurrencyId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "SellingCurrency")]
            public Currency SellingCurrency { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "UnitPrice2")]
            public decimal UnitPrice2 { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "SellingCurrency2Id")]
            public int SellingCurrency2Id { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "SellingCurrency2")]
            public Currency SellingCurrency2 { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingPrice")]
            public decimal BuyingPrice { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingCurrencyId")]
            public int BuyingCurrencyId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingCurrency")]
            public Currency BuyingCurrency { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingPrice2")]
            public decimal BuyingPrice2 { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingCurrency2Id")]
            public int BuyingCurrency2Id { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "BuyingCurrency2")]
            public Currency BuyingCurrency2 { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "LicensorPrice")]
            public decimal LicensorPrice { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "LicensorCurrencyId")]
            public int LicensorCurrencyId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "LicensorCurrency")]
            public Currency LicensorCurrency { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RoyaltyFee")]
            public decimal RoyaltyFee { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RoyaltyCurrencyId")]
            public int RoyaltyCurrencyId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RoyaltyCurrency")]
            public Currency RoyaltyCurrency { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RetailPrice")]
            public decimal RetailPrice { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RetailCurrencyId")]
            public int RetailCurrencyId { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "RetailCurrency")]
            public Currency RetailCurrency { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "PurchaseOrders")]
            public ICollection<PurchaseOrder> PurchaseOrders { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "Suppliers")]
            public ICollection<Supplier> Suppliers { get; set; }

            [UIHint("BoolRed")]
            [Display(ResourceType = typeof(EntityStrings), Name = "Discontinued")]
            public bool Discontinued { get; set; }

            [DataType(DataType.Date)]
            [Display(ResourceType = typeof(EntityStrings), Name = "DiscontinueDate")]
            public DateTime DiscontinueDate { get; set; }

            [StringLength(256, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxLeght")]
            [DataType(DataType.MultilineText)]
            [Display(ResourceType = typeof(EntityStrings), Name = "DiscontinueNotes")]
            public string DiscontinueNotes { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "DiscontinuedUser")]
            public AspNetUser DiscontinuedUser { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "ModifiedUser")]
            public AspNetUser ModifiedUser { get; set; }

            [Display(ResourceType = typeof(EntityStrings), Name = "CreatedUser")]
            public AspNetUser CreatedUser { get; set; }

		}
	}
}